language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer update

script: composer test

matrix:
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
services:
  - mysql
